### ISSUE TITLE
Ошибка Message: no such element: Unable to locate element: {"method":"css selector","selector":"#teacher-school-invite > div.ts-invite__footer > button"}

### ISSUE THREAD

**Issue by RomanMironenko** [kartingist/urait_book_downloader#1]
Добрый день! Пытаюсь скачать книгу с помощью скрипта и выходит ошибка 'Message: no such element: Unable to locate element: {"method":"css selector","selector":"#teacher-school-invite > div.ts-invite__footer > button"}'. Что сделать, чтобы ее исправить?

**Comment by kartingist** [comment]
Привет, проекту года 2, возможно за это время сайт изменил верстку и теперь
скрипт не может найти элемент

сб, 9 дек. 2023 г., 17:16 Roman Mironenko ***@***.***>:

**Comment by kartingist** [comment]
добавил правки, должно работать, но у меня нет подписки чтобы точно проверить
